FROM node:18-alpine
WORKDIR /var/www

# Install dependencies required for node-gyp
RUN apk add --no-cache python3 make g++ && \
    ln -sf /usr/bin/python3 /usr/bin/python

# Set npm_config_python to ensure node-gyp uses the correct Python
ENV npm_config_python=/usr/bin/python3

COPY package*.json .
RUN npm install
COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev"]