name: Web3PairProject
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www/
    networks:
      - web3pairproject
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/var/www/
    container_name: frontend
    ports:
      - 5173:5173
    depends_on:
      - backend
    networks:
      - web3pairproject
networks:
  web3pairproject:
    driver: bridge