[tool.ruff]
line-length = 120
lint.extend-select = ["C4", "N", "B", "SIM", "W291", "W293", "I"]
lint.ignore = ["F401"]
show-fixes = true
target-version = "py39"
exclude = ["**/.venv", "**/__pycache__"]

[tool.ruff.format]
quote-style = "single"
indent-style = "tab"
docstring-code-format = true
docstring-code-line-length = 20
