"""add-uploads-and-ifps-cache

Revision ID: a670eff8b798
Revises: b3d98ae46bce
Create Date: 2024-12-23 14:14:40.299423

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a670eff8b798'
down_revision = 'b3d98ae46bce'
branch_labels = None
depends_on = None

import os

environment = os.getenv('FLASK_ENV')
SCHEMA = os.environ.get('SCHEMA')


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'ipfs_cache',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('ipfs_hash', sa.String(length=255), nullable=False),
		sa.Column('uploaded_at', sa.DateTime(), nullable=False),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_table(
		'uploads',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('owner_id', sa.Integer(), nullable=False),
		sa.Column('name', sa.String(length=255), nullable=False),
		sa.Column('size', sa.Integer(), nullable=False),
		sa.Column('ipfs_hash', sa.String(length=255), nullable=False),
		sa.Column('timestamp', sa.String(length=255), nullable=False),
		sa.Column('gateway_url', sa.String(length=255), nullable=False),
		sa.Column('upload_metadata', sa.JSON(), nullable=False),
		sa.ForeignKeyConstraint(
			['owner_id'],
			['users.id'],
		),
		sa.PrimaryKeyConstraint('id'),
	)

	if environment == 'production':
		op.execute(f'ALTER TABLE users SET SCHEMA {SCHEMA};')
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('uploads')
	op.drop_table('ipfs_cache')
	# ### end Alembic commands ###
