"""wallet table updated

Revision ID: e87132512a2b
Revises: b3d98ae46bce
Create Date: 2024-12-19 10:43:54.481820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87132512a2b'
down_revision = 'b3d98ae46bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_key', sa.Text(), nullable=True))
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.TEXT(), nullable=False))
        batch_op.drop_column('wallet_key')

    # ### end Alembic commands ###
