name: Lint and Format

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff for Python linting and formatting
        run: |
          ruff check backend/app --fix
        continue-on-error: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: npm install
        working-directory: frontend

      - name: Run ESLint for JavaScript linting
        run: npx eslint src/
        working-directory: frontend
        continue-on-error: true

      - name: Run Prettier for JavaScript formatting
        run: npx prettier src --check
        working-directory: frontend
        continue-on-error: true

      - name: Upload linting and formatting results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: lint-and-format-results
          path: |
            backend/app
            frontend/src